import "dotenv/config"
import { PrismaClient } from "../src/generated/prisma/client"
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3"
import bcrypt from "bcryptjs"

const adapter = new PrismaBetterSqlite3({ url: "file:./dev.db" })
const db = new PrismaClient({ adapter })

const products = [
  {
    slug: "bd-av-1pc-1yr",
    name: "Bitdefender Antivirus Plus — 1 PC, 1 Year",
    shortName: "Antivirus Plus",
    category: "ANTIVIRUS" as const,
    devices: 1,
    months: 12,
    price: 249.0,
    comparePrice: 369.0,
    imageFile: "Bitdefender-ESD-AV-1-12-EN.jpg",
    description:
      "Bitdefender Antivirus Plus delivers powerful, real-time protection against viruses, spyware, ransomware, and other threats. Features include advanced threat defense, anti-phishing, and web filtering.",
    features: JSON.stringify([
      "Real-time threat protection",
      "Anti-phishing & web filtering",
      "Ransomware protection",
      "Advanced threat defense",
      "Safe online banking",
      "Vulnerability scanner",
    ]),
    platforms: JSON.stringify(["windows"]),
    isFeatured: true,
    sortOrder: 10,
  },
  {
    slug: "bd-av-2pc-1yr",
    name: "Bitdefender Antivirus Plus — 2 PCs, 1 Year",
    shortName: "Antivirus Plus",
    category: "ANTIVIRUS" as const,
    devices: 2,
    months: 12,
    price: 349.0,
    comparePrice: 519.0,
    imageFile: "Bitdefender-ESD-AV-2-12-EN.jpg",
    description:
      "Protect 2 PCs with Bitdefender Antivirus Plus. Award-winning antivirus with real-time protection, anti-phishing, safe banking, and ransomware defense.",
    features: JSON.stringify([
      "Real-time threat protection",
      "Anti-phishing & web filtering",
      "Ransomware protection",
      "Advanced threat defense",
      "Safe online banking",
      "Vulnerability scanner",
    ]),
    platforms: JSON.stringify(["windows"]),
    isFeatured: false,
    sortOrder: 11,
  },
  {
    slug: "bd-av-3pc-1yr",
    name: "Bitdefender Antivirus Plus — 3 PCs, 1 Year",
    shortName: "Antivirus Plus",
    category: "ANTIVIRUS" as const,
    devices: 3,
    months: 12,
    price: 449.0,
    comparePrice: 649.0,
    imageFile: "Bitdefender-ESD-AV-3-12-EN.jpg",
    description:
      "Protect 3 PCs with Bitdefender Antivirus Plus. Award-winning antivirus with real-time protection, anti-phishing, safe banking, and ransomware defense.",
    features: JSON.stringify([
      "Real-time threat protection",
      "Anti-phishing & web filtering",
      "Ransomware protection",
      "Advanced threat defense",
      "Safe online banking",
      "Vulnerability scanner",
    ]),
    platforms: JSON.stringify(["windows"]),
    isFeatured: false,
    sortOrder: 12,
  },
  {
    slug: "bd-av-5pc-1yr",
    name: "Bitdefender Antivirus Plus — 5 PCs, 1 Year",
    shortName: "Antivirus Plus",
    category: "ANTIVIRUS" as const,
    devices: 5,
    months: 12,
    price: 599.0,
    comparePrice: 879.0,
    imageFile: "Bitdefender-ESD-AV-5-12-EN.jpg",
    description:
      "Protect 5 PCs with Bitdefender Antivirus Plus. Award-winning antivirus with real-time protection, anti-phishing, safe banking, and ransomware defense.",
    features: JSON.stringify([
      "Real-time threat protection",
      "Anti-phishing & web filtering",
      "Ransomware protection",
      "Advanced threat defense",
      "Safe online banking",
      "Vulnerability scanner",
    ]),
    platforms: JSON.stringify(["windows"]),
    isFeatured: false,
    sortOrder: 13,
  },
  {
    slug: "bd-is-1pc-1yr",
    name: "Bitdefender Internet Security — 1 PC, 1 Year",
    shortName: "Internet Security",
    category: "INTERNET_SECURITY" as const,
    devices: 1,
    months: 12,
    price: 349.0,
    comparePrice: 519.0,
    imageFile: "Bitdefender-ESD-IS-1-12-EN (1).jpg",
    description:
      "Bitdefender Internet Security protects your PC with all the antivirus features plus a two-way firewall, parental controls, privacy tools, and webcam protection.",
    features: JSON.stringify([
      "Everything in Antivirus Plus",
      "Two-way firewall",
      "Parental controls",
      "Webcam & microphone protection",
      "Anti-tracker",
      "File shredder",
    ]),
    platforms: JSON.stringify(["windows"]),
    isFeatured: true,
    sortOrder: 20,
  },
  {
    slug: "bd-is-2pc-1yr",
    name: "Bitdefender Internet Security — 2 PCs, 1 Year",
    shortName: "Internet Security",
    category: "INTERNET_SECURITY" as const,
    devices: 2,
    months: 12,
    price: 469.0,
    comparePrice: 699.0,
    imageFile: "Bitdefender-ESD-IS-2-12-EN.jpg",
    description:
      "Protect 2 PCs with Bitdefender Internet Security. Includes firewall, parental controls, webcam protection, and all antivirus features.",
    features: JSON.stringify([
      "Everything in Antivirus Plus",
      "Two-way firewall",
      "Parental controls",
      "Webcam & microphone protection",
      "Anti-tracker",
      "File shredder",
    ]),
    platforms: JSON.stringify(["windows"]),
    isFeatured: false,
    sortOrder: 21,
  },
  {
    slug: "bd-is-3pc-1yr",
    name: "Bitdefender Internet Security — 3 PCs, 1 Year",
    shortName: "Internet Security",
    category: "INTERNET_SECURITY" as const,
    devices: 3,
    months: 12,
    price: 589.0,
    comparePrice: 879.0,
    imageFile: "Bitdefender-ESD-IS-3-12-EN.jpg",
    description:
      "Protect 3 PCs with Bitdefender Internet Security. Includes firewall, parental controls, webcam protection, and all antivirus features.",
    features: JSON.stringify([
      "Everything in Antivirus Plus",
      "Two-way firewall",
      "Parental controls",
      "Webcam & microphone protection",
      "Anti-tracker",
      "File shredder",
    ]),
    platforms: JSON.stringify(["windows"]),
    isFeatured: false,
    sortOrder: 22,
  },
  {
    slug: "bd-is-5pc-1yr",
    name: "Bitdefender Internet Security — 5 PCs, 1 Year",
    shortName: "Internet Security",
    category: "INTERNET_SECURITY" as const,
    devices: 5,
    months: 12,
    price: 749.0,
    comparePrice: 1099.0,
    imageFile: "Bitdefender-ESD-IS-5-12-EN.jpg",
    description:
      "Protect 5 PCs with Bitdefender Internet Security. Includes firewall, parental controls, webcam protection, and all antivirus features.",
    features: JSON.stringify([
      "Everything in Antivirus Plus",
      "Two-way firewall",
      "Parental controls",
      "Webcam & microphone protection",
      "Anti-tracker",
      "File shredder",
    ]),
    platforms: JSON.stringify(["windows"]),
    isFeatured: false,
    sortOrder: 23,
  },
  {
    slug: "bd-ts-3pc-1yr",
    name: "Bitdefender Total Security — 3 Devices, 1 Year",
    shortName: "Total Security",
    category: "TOTAL_SECURITY" as const,
    devices: 3,
    months: 12,
    price: 649.0,
    comparePrice: 949.0,
    imageFile: "Bitdefender-ESD-TS-3-12-EN (1).jpg",
    description:
      "Bitdefender Total Security is our best multi-device protection, covering Windows, Mac, iOS, and Android. Includes all features plus optimization tools and anti-theft.",
    features: JSON.stringify([
      "Windows, Mac, iOS & Android",
      "Anti-theft protection",
      "Device optimization tools",
      "Parental controls",
      "Webcam & mic protection",
      "VPN (200 MB/day)",
    ]),
    platforms: JSON.stringify(["windows", "mac", "android", "ios"]),
    isFeatured: true,
    sortOrder: 30,
  },
  {
    slug: "bd-ts-5pc-1yr",
    name: "Bitdefender Total Security — 5 Devices, 1 Year",
    shortName: "Total Security",
    category: "TOTAL_SECURITY" as const,
    devices: 5,
    months: 12,
    price: 849.0,
    comparePrice: 1249.0,
    imageFile: "Bitdefender-ESD-TS-5-12-EN.jpg",
    description:
      "Protect 5 devices across Windows, Mac, iOS, and Android with Bitdefender Total Security. The most complete protection with performance optimization and anti-theft.",
    features: JSON.stringify([
      "Windows, Mac, iOS & Android",
      "Anti-theft protection",
      "Device optimization tools",
      "Parental controls",
      "Webcam & mic protection",
      "VPN (200 MB/day)",
    ]),
    platforms: JSON.stringify(["windows", "mac", "android", "ios"]),
    isFeatured: true,
    sortOrder: 31,
  },
  {
    slug: "bd-fp-15pc-1yr",
    name: "Bitdefender Family Pack — 15 Devices, 1 Year",
    shortName: "Family Pack",
    category: "FAMILY_PACK" as const,
    devices: 15,
    months: 12,
    price: 1199.0,
    comparePrice: 1749.0,
    imageFile: "Bitdefender-ESD-FP-15-12-EN (3).jpg",
    description:
      "Keep your whole family safe on up to 15 devices. Bitdefender Family Pack includes Total Security features plus comprehensive parental controls for every child's device.",
    features: JSON.stringify([
      "Up to 15 devices",
      "Windows, Mac, iOS & Android",
      "Advanced parental controls",
      "Screen time management",
      "Anti-theft for all devices",
      "Device optimization tools",
    ]),
    platforms: JSON.stringify(["windows", "mac", "android", "ios"]),
    isFeatured: true,
    sortOrder: 40,
  },
  {
    slug: "bd-mac-1pc-1yr",
    name: "Bitdefender Antivirus for Mac — 1 Mac, 1 Year",
    shortName: "Antivirus for Mac",
    category: "MAC" as const,
    devices: 1,
    months: 12,
    price: 299.0,
    comparePrice: 449.0,
    imageFile: "Bitdefender-ESD-MAC-1-12-EN.jpg",
    description:
      "Bitdefender Antivirus for Mac provides ultra-fast protection without slowing your Mac down. Stops adware, ransomware, and cross-platform threats.",
    features: JSON.stringify([
      "Real-time Mac protection",
      "Adware & ransomware defense",
      "Time Machine protection",
      "Anti-phishing",
      "Safe browsing",
      "Low system impact",
    ]),
    platforms: JSON.stringify(["mac"]),
    isFeatured: false,
    sortOrder: 50,
  },
  {
    slug: "bd-mac-3pc-1yr",
    name: "Bitdefender Antivirus for Mac — 3 Macs, 1 Year",
    shortName: "Antivirus for Mac",
    category: "MAC" as const,
    devices: 3,
    months: 12,
    price: 499.0,
    comparePrice: 749.0,
    imageFile: "Bitdefender-ESD-MAC-3-12-EN (1).jpg",
    description:
      "Protect 3 Macs with Bitdefender's award-winning Mac security. Stops adware, ransomware, and cross-platform threats with zero performance impact.",
    features: JSON.stringify([
      "Real-time Mac protection",
      "Adware & ransomware defense",
      "Time Machine protection",
      "Anti-phishing",
      "Safe browsing",
      "Low system impact",
    ]),
    platforms: JSON.stringify(["mac"]),
    isFeatured: false,
    sortOrder: 51,
  },
  {
    slug: "bd-ms-1dev-1yr",
    name: "Bitdefender Mobile Security — 1 Device, 1 Year",
    shortName: "Mobile Security",
    category: "MOBILE_SECURITY" as const,
    devices: 1,
    months: 12,
    price: 199.0,
    comparePrice: 299.0,
    imageFile: "Bitdefender-ESD-MS-1-12-EN (1).jpg",
    description:
      "Bitdefender Mobile Security for Android and iOS keeps your device and personal data safe. Includes malware scanning, web protection, anti-theft, and app lock.",
    features: JSON.stringify([
      "Malware scanner",
      "Web protection",
      "Anti-theft & device lock",
      "App lock",
      "WearON (smartwatch alerts)",
      "Account privacy checker",
    ]),
    platforms: JSON.stringify(["android", "ios"]),
    isFeatured: false,
    sortOrder: 60,
  },
  {
    slug: "bd-psw",
    name: "Bitdefender Password Manager",
    shortName: "Password Manager",
    category: "PASSWORD_MANAGER" as const,
    devices: null,
    months: 12,
    price: 179.0,
    comparePrice: 269.0,
    imageFile: "Bitdefender-ESD-PSW-MANAGER-EN.jpg",
    description:
      "Bitdefender Password Manager securely stores and auto-fills your passwords across all browsers and devices. Includes breach alerts and strong password generator.",
    features: JSON.stringify([
      "Unlimited password storage",
      "Auto-fill on all browsers",
      "Password breach alerts",
      "Strong password generator",
      "Secure notes",
      "Cross-device sync",
    ]),
    platforms: JSON.stringify(["windows", "mac", "android", "ios"]),
    isFeatured: false,
    sortOrder: 70,
  },
  {
    slug: "bd-soho-5pc-1yr",
    name: "Bitdefender Small Office Security — 5 Devices, 1 Year",
    shortName: "Small Office Security",
    category: "SOHO" as const,
    devices: 5,
    months: 12,
    price: 899.0,
    comparePrice: 1299.0,
    imageFile: "Bitdefender-ESD-SOHO-5-12-EN.jpg",
    description:
      "Bitdefender Small Office Security protects your business PCs, Macs, and mobiles. Includes a web-based management console for easy oversight of all devices.",
    features: JSON.stringify([
      "5 device licenses",
      "Web management console",
      "Advanced threat defense",
      "Email protection",
      "Network threat prevention",
      "Priority support",
    ]),
    platforms: JSON.stringify(["windows", "mac", "android", "ios"]),
    isFeatured: false,
    sortOrder: 80,
  },
  {
    slug: "bd-soho-10pc-1yr",
    name: "Bitdefender Small Office Security — 10 Devices, 1 Year",
    shortName: "Small Office Security",
    category: "SOHO" as const,
    devices: 10,
    months: 12,
    price: 1499.0,
    comparePrice: 2199.0,
    imageFile: "Bitdefender-ESD-SOHO-10-12-EN.jpg",
    description:
      "Protect your entire small office with Bitdefender Security for up to 10 devices. Centrally managed protection with advanced threat defense and email security.",
    features: JSON.stringify([
      "10 device licenses",
      "Web management console",
      "Advanced threat defense",
      "Email protection",
      "Network threat prevention",
      "Priority support",
    ]),
    platforms: JSON.stringify(["windows", "mac", "android", "ios"]),
    isFeatured: false,
    sortOrder: 81,
  },
  {
    slug: "bd-soho-20pc-1yr",
    name: "Bitdefender Small Office Security — 20 Devices, 1 Year",
    shortName: "Small Office Security",
    category: "SOHO" as const,
    devices: 20,
    months: 12,
    price: 2499.0,
    comparePrice: 3699.0,
    imageFile: "Bitdefender-ESD-SOHO-20-12-EN.jpg",
    description:
      "Comprehensive business protection for up to 20 devices. Centrally managed via the web console with advanced threat defense, network protection, and priority support.",
    features: JSON.stringify([
      "20 device licenses",
      "Web management console",
      "Advanced threat defense",
      "Email protection",
      "Network threat prevention",
      "Priority support",
    ]),
    platforms: JSON.stringify(["windows", "mac", "android", "ios"]),
    isFeatured: false,
    sortOrder: 82,
  },
  {
    slug: "bd-vpn-5dev-1yr",
    name: "Bitdefender VPN — 5 Devices, 1 Year",
    shortName: "VPN",
    category: "VPN" as const,
    devices: 5,
    months: 12,
    price: 299.0,
    comparePrice: 449.0,
    imageFile: "Bitdefender-ESD-VPN-5-12-EN.jpg",
    description:
      "Bitdefender VPN provides fast, secure browsing on up to 5 devices. Encrypts your connection, hides your IP, and lets you access content from around the world.",
    features: JSON.stringify([
      "Unlimited traffic",
      "AES 256-bit encryption",
      "50+ server locations",
      "No activity logs",
      "Kill switch",
      "Ad blocker",
    ]),
    platforms: JSON.stringify(["windows", "mac", "android", "ios"]),
    isFeatured: false,
    sortOrder: 90,
  },
  {
    slug: "bd-vpn-10dev-1yr",
    name: "Bitdefender VPN — 10 Devices, 1 Year",
    shortName: "VPN",
    category: "VPN" as const,
    devices: 10,
    months: 12,
    price: 449.0,
    comparePrice: 679.0,
    imageFile: "Bitdefender-ESD-VPN-10-12-EN (1).jpg",
    description:
      "Protect all your devices with Bitdefender VPN for 10 devices. Unlimited traffic, AES 256-bit encryption, and 50+ server locations worldwide.",
    features: JSON.stringify([
      "Unlimited traffic",
      "AES 256-bit encryption",
      "50+ server locations",
      "No activity logs",
      "Kill switch",
      "Ad blocker",
    ]),
    platforms: JSON.stringify(["windows", "mac", "android", "ios"]),
    isFeatured: false,
    sortOrder: 91,
  },
]

async function main() {
  console.log("Seeding database...")

  for (const product of products) {
    await db.product.upsert({
      where: { slug: product.slug },
      update: product,
      create: product,
    })
    console.log(`  ✓ ${product.name}`)
  }

  const adminEmail = process.env.ADMIN_EMAIL ?? "admin@apptechies.co.za"
  const adminPassword = process.env.ADMIN_PASSWORD ?? "changeme123"
  const hash = await bcrypt.hash(adminPassword, 10)

  await db.adminUser.upsert({
    where: { email: adminEmail },
    update: { passwordHash: hash },
    create: { email: adminEmail, passwordHash: hash },
  })
  console.log(`  ✓ Admin user: ${adminEmail}`)

  console.log("\nSeed complete!")
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(() => db.$disconnect())
